if(NOT USE_CUDA_LITE STREQUAL "OFF")
  if(NOT IS_DIRECTORY ${USE_CUDA_LITE})
    message(FATAL_ERROR "Please specify bsg_bladerunner root path in config.cmake")
  elseif(IS_DIRECTORY ${USE_CUDA_LITE})
    set(BSG_BLADERUNNER_ROOT ${USE_CUDA_LITE})
    configure_file(cmake/cuda_lite.makefile ../hb/cuda_lite_compile/Makefile)
    message(STATUS "Build with CUDA-Lite support...")
    list(APPEND COMPILER_SRCS src/codegen/opt/build_cuda_lite_on.cc)

    string(CONCAT BSG_F1_DIR ${BSG_BLADERUNNER_ROOT} "/bsg_f1")
    string(CONCAT HBMC_INCLUDE_DIRS ${BSG_F1_DIR} "/cl_manycore/libraries/")
    include_directories(${HBMC_INCLUDE_DIRS})
    file(GLOB RUNTIME_HB_SRCS src/runtime/hbmc/*.cc)
    list(APPEND RUNTIME_SRCS ${RUNTIME_HB_SRCS})

    string(CONCAT HBMC_HBMC_LIBRARY ${BSG_F1_DIR} "/cl_manycore/libraries/libbsg_manycore_runtime.so")
    list(APPEND TVM_RUNTIME_LINKER_LIBS ${HBMC_HBMC_LIBRARY})
  endif(USE_CUDA_LITE)
endif(USE_CUDA_LITE)
